template = "https://github.com/giellalt/template-lang-und"
rev_id = 117
template_sha = "32744b7a96e8c2391415cb499d7f5f028750e3d4"

[replacements]
__REPO__ = "lang-kal"
__UND2C__ = "kl"
__UNDEFINED__ = "Kalaallisut"
__UND__ = "kal"
