template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "kala1399"
__REPO__ = "lang-kal"
__UND2C__ = "kl"
__UNDEFINED__ = "Kalaallisut"
__UND__ = "kal"
