template = "https://github.com/giellalt/template-lang-und"
rev_id = 118
template_sha = "9e11bbebb1343270ebe41747fc2d41d8f789dec5"

[replacements]
__REPO__ = "lang-kal"
__UND2C__ = "kl"
__UNDEFINED__ = "Kalaallisut"
__UND__ = "kal"
