template = "https://github.com/giellalt/template-lang-und"
rev_id = 126
template_sha = "ad3624086df0730923a482ae4a48948c2ea37419"

[replacements]
__REPO__ = "lang-kal"
__UND2C__ = "kl"
__UNDEFINED__ = "Kalaallisut"
__UND__ = "kal"
